<?php
/**@var $viewModel Task\PriceVisibilityRestriction\ViewModel\ShowPriceButton */
$viewModel = $block->getViewModel();;
?>
    <button id="show-price-button" type="button"
            class="<?php echo $block->escapeHtml($viewModel->setBtnClass()); ?>"
            data-product-id="<?php echo $viewModel->getCurrentProduct(); ?>"
            <?php if ($viewModel->isUserGuest()): ?>
                onclick="location.href = '<?php echo $block->getUrl('price_request/guest/redirect'); ?>'"
            <?php endif; ?>
    >
            <?php echo $block->escapeHtml('Show price') ?>
    </button>
    <script type="text/x-magento-init">
    {
        "*": {
            "Task_PriceVisibilityRestriction/js/show-price" : {
            }
        }
    }
    </script>
