<?php
/** @var \Task\ProductCommentModule\Block\Comment $block */
?>
<div class="comment-block">
    <div class="form-container">
        <form class="form" id="my-form" action="<?php echo $block->getUrl('task/form/submit') ?>" method="post">
            <label for="nickname">Nickname</label>
            <input class="input" type="text" name="nickname" id="nickname" placeholder="Your nickname" value="<?php echo $block->escapeHtml($block->getUserData('name'));?>">
            <label for="email">Email address</label>
            <input class="input" type="email" name="email" id="email" placeholder="Your email" value="<?php echo $block->escapeHtml($block->getUserData('email'));?>">
            <label for="text">Comment</label>
            <textarea class="input" id="text" rows="3" name="text"></textarea>
            <button class="button" type="submit">Submit</button>
        </form>
    </div>
    <?php if ($block->getItems()): ?>
        <ul class="comment-list">
            <?php foreach ($block->getItems() as $item): ?>
                <li class="comment-item">
                    <p class="comment">
                        <?php echo $item->getText(); ?>
                    </p>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p class="error-message">Database Not contains the comment for this product.</p>
    <?php endif; ?>
</div>
